### ISSUE TITLE
Trim trailing slashes from URLs?

### ISSUE THREAD

**Issue by martimpassos** [dnoneill/annonatate-sourcecode#25]
Hi @dnoneill, this is probably my problem but it might be something you want to implement. My manifests `service` `id` accidentally contained a trailing `/`: 
```
"service": [
  {
    "id": "https://imaginerio-images.s3.us-east-1.amazonaws.com/iiif/0071824cxrio3-04/",
```
which led annonatate to look for `https://imaginerio-images.s3.us-east-1.amazonaws.com/iiif/0071824cxrio3-04//info.json` that obviously doesn't exist. The same manifest displays fine in Mirador, so I'm assuming they do some kind of checking/sanitizing that you might be interested in adopting

**Comment by dnoneill** [comment]
@martimpassos Done and deployed.
