### ISSUE TITLE
Using the [DEL] key to delete one character within an annotation's comment causes the whole annotation to be deleted.

### ISSUE THREAD

**Issue by Pigeo** [dnoneill/annonatate-sourcecode#39]
Tested in 3 different browsers (Safari / Firefox / Chrome)

When typing or editing an annotation's comment (be it an already existing annotation or a new one just being created), pressing the DEL key on the keyboard deletes the whole annotation instead of just deleting one character in the annotation's comment.

This is VERY annoying bug, considering that there's currently no way to undo the deletion of an annotation.

**Comment by Pigeo** [comment]
In the meantime, I found a proper work-around to disable the DEL key on Annonatate:

1. Install [Shortkeys (Custom Keyboard Shortcuts)](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck) extension for Firefox or Google Chrome.
2. Configure it as follows:
![Capture d’écran 2023-07-21 à 17 54 14](https://github.com/dnoneill/annonatate-sourcecode/assets/6595324/a873374d-3bc9-436f-a13f-d5e6cab24a9a)
(caveat: the "do nothing" option doesn't work, you have to choose some action that steals the focus from the webpage)
3. Close and reopen Annonatate, and voilà!

**Comment by dnoneill** [comment]
@Pigeo if you could please attach a screen recording of this along with information about why kind of machine and keyboard you are using. I have not been able to replicate this issue.

@rsimon

**Comment by Pigeo** [comment]
Here is the [screen recording](https://filesender.renater.fr/?s=download&lang=en&token=2f4a414f-692a-41d0-8bca-f2bc9672c0a4) (available for download until 21th August).

Obviously, you need to use an USB keyboard from a desktop computer in order to have the DEL key on it (otherwise, most laptop keyboards don't have a DEL key, but sometimes you can simulate it by pressing a combination such as Fn + Backspace).

FYI, I also tried on a completely different machine (Firefox running on Windows 10 PC), and the issue is exactly the same, so I don't think it depends on the machine/keyboard you are using (as long as you have a keyboard with the DEL key on it, of course).
