### ISSUE TITLE
Support for imported vocabulary

### ISSUE THREAD

**Issue by martimpassos** [dnoneill/annonatate-sourcecode#4]
Uploading a CSV would be the best from an approachability perspective, IMO. Annonatate can parse it internally to create the JSON array used to initialize Annotorious. Where would be the best place for this to sit on? On the user profile tab, next to Workspace settings?

**Comment by dnoneill** [comment]
@martimpassos I have not deployed this functionality yet (leaning towards Thursday, my Wednesday is packed), but I have coded it. The instructions are as follows, upload a CSV with a "label" and "uri" column, the uri column does not always have to be filled out. The application will then upload that into a yml in your GitHub repository. You can also edit the file in the profile tab. Let me know if you have any feedback.

**Comment by martimpassos** [comment]
Hi @dnoneill thanks so much for implementing this. We have put our annotation project a bit on hold as we decide on the vocabulary and entities to use, but I'll definitely give this a go sometime soon and provide some feedback. Thanks again!
