### ISSUE TITLE
Can not move a point on an already existing annotation

### ISSUE THREAD

**Issue by Pigeo** [dnoneill/annonatate-sourcecode#52]
Trying to move a point on an already existing annotation (be it rectangular or polygon, be it mine or someone else's annotation), the web browser's javascript console says: 
```
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'args.annotation.target.selector')
    __e (openseadragon-annotorious.min.js:1:10406)
    (fonction anonyme) (openseadragon-annotorious.min.js:1:15173)
    cr (openseadragon-annotorious.min.js:1:7383)
    (fonction anonyme) (openseadragon-annotorious.min.js:1:2545)
    some
    Yn (openseadragon-annotorious.min.js:1:2444)
```
(Safari version)
```
Uncaught (in promise) TypeError: args.annotation.target is null
    convertToPolygonWidget index.js:927
    renderWidget WrappedWidget.jsx:12
    componentWillReceiveProps WrappedWidget.jsx:39
    Preact 19
```
(Firefox version)

After that, a lot of things in the User Interface start to become malfunctioning (unresponsive), and eventually, I get another error in the console :
```
[Error] TypeError: undefined is not an object (evaluating 'e.key')
or — vue@2.6.14:6:42236
(fonction anonyme) — vue@2.6.14:6:60074
x — vue@2.6.14:6:60234
(fonction anonyme) — vue@2.6.14:6:61370
(fonction anonyme) — vue@2.6.14:6:34602
r — vue@2.6.14:6:68563
(fonction anonyme) — vue@2.6.14:6:26872
(fonction anonyme) — vue@2.6.14:6:27755
ln — vue@2.6.14:6:25863
(fonction anonyme) — vue@2.6.14:6:12481
We — vue@2.6.14:6:11878

    Ve (vue@2.6.14:6:11768)
    Ue (vue@2.6.14:6:11681)
    He (vue@2.6.14:6:11333)
    (fonction anonyme) (vue@2.6.14:6:12496)
    We (vue@2.6.14:6:11878)
```

I'm pretty sure this bug wasn't there a couple of weeks ago. 

Yesterday, some of our students have reported to me : "Since a couple of days, I've been having a few problems with annonatate. Some annotations disappear, reappear or don't seem to save. I don't know if you've noticed this phenomenon yourself, but I hope it doesn't affect you, as I can't work out what's actually being saved in the annotations I've made." (translated from French). I don't know for the moment if she was referring to this particular bug or to another one ?

**Comment by dnoneill** [comment]
@Pigeo This problem is going to take longer than I thought. It looks like this is an issue with all polygons not just the converted ones and it is coming from the annotorious plugin. I have opened an issue in the code and will look into in the next couple of days but it isn't going to be as quick as the other issue.

**Comment by Pigeo** [comment]
What do you mean exactly by "converted ones" ? (I thought the conversion feature between rectangle and polygon isn't yet available, is it ?)
Strangely enough, I'm pretty sure this bug wasn't there a couple of weeks ago, as I still remember correcting a lot of polygon points that were misaligned on existing annotations.
=> could it be a regression introduced by #51 (or a regression in the latest version of the annotorious plugin)?
I understand it will take more time to fix this issue. Hopefully, the other one which is already fixed was the most critical for us.

**Comment by dnoneill** [comment]
@Pigeo The conversion feature between rectangle and polygon is available. You should see it as an option for any rectangles. Thanks for your comment. Based on the way the error was being displayed in the console it looked like the issue was coming from annotorious but it was actually coming from the recttopolygon widget and I was able to fix and deploy this issue. Should be working now.

**Comment by Pigeo** [comment]
👍 very nice! I've only just seen it.
