### ISSUE TITLE
Previous annotations not shown (neither in Search tab nor in Start Annotating)

### ISSUE THREAD

**Issue by Pigeo** [dnoneill/annonatate-sourcecode#53]
I have made some annotations some months ago, that now do correctly appear in the "Annotations" tab, however they don't appear neither in Search tab nor in the List View or on the canvas of the annotorious viewer (when going in Home tab => start annotating => going to the right page)
See screen shots attached:
![Capture d’écran 2023-09-27 à 12 21 44](https://github.com/dnoneill/annonatate-sourcecode/assets/6595324/d03baa1b-8610-4714-8996-083dea98b605)
![Capture d’écran 2023-09-27 à 12 19 41](https://github.com/dnoneill/annonatate-sourcecode/assets/6595324/9fed82c0-b38c-4203-9a2e-f3db49fd71fb)
![Capture d’écran 2023-09-27 à 12 29 19](https://github.com/dnoneill/annonatate-sourcecode/assets/6595324/ce1bf45a-94f6-4a10-b615-606084282d47)

**Comment by Pigeo** [comment]
When I look into folder `/_annotations/`, I see 990 files in the form of a UUID.json : 
```
> ls *-????-????-????-*.json | wc -l
990
```
(+ 312 files with the pattern `bcl-180-unice-fr-11280-XXXXN-XXXX-N-NNNN-list.json`)

Whereas when I go in the "Search" tab, it says: "Showing 720 annotations out of 720 annotations"

=> it seems that 270 annotations are missing from the Graphical User Interface?

**Comment by Pigeo** [comment]
Same thing in the "Annotations" tab (image viewer + single annotation): 720 occurrences of "is part of"
(which is strange because, as demonstrated above, some annotations are shown in the "Annotations" tab but not in the "Search" tab, so I would have expected to have different totals for each of these tabs)

**Comment by Pigeo** [comment]
Ok, I made a 1-to-1 comparison between what I have in folder `/_annotations/` and what is displayed in the "Annotations" tab (image viewer + single annotation) and here is where the difference resides (see screenshot attached): 
- all the 720 annotations correctly displayed in Annonatate have their UUID below  `bd000000-0000-0000-0000-000000000000`
- all the missing 270 annotations have their UUID above `bd000000-0000-0000-0000-000000000000`

=> it seems that the Graphical User Interface no longer handles properly all the annotations having a UUID above `bd000000-0000-0000-0000-000000000000` (I'm pretty sure this bug wasn't there some weeks ago)

![Capture d’écran 2023-09-27 à 16 21 55](https://github.com/dnoneill/annonatate-sourcecode/assets/6595324/a2e4135b-87be-4ca4-bddf-a17a7ebce664)

**Comment by dnoneill** [comment]
@Pigeo It will be faster if I can see the repository you are using. Anyway you can share that with me? Thanks!

**Comment by Pigeo** [comment]
If you know the UUID of an annotation, and you try to get it through its URL, it also doesn't work:
[This one works because `a2256a…` < `bd0000…`](https://annonatate.fly.dev/annotations/a2256add-12b7-4046-aee7-777629850c0d.json)
[This one doesn't work because `e1529a…` > `bd0000…`](https://annonatate.fly.dev/annotations/e1529add-edab-4418-97de-f2ee2e92762d.json)
[Neither this one, for the same reason](https://annonatate.fly.dev/annotations/f6a1cd84-3466-4128-af7d-afc84e93a664.json)

**Comment by Pigeo** [comment]
> @Pigeo It will be faster if I can see the repository you are using. Anyway you can share that with me? Thanks!

Yes, of course: it's [this one](https://github.com/pag06/atlas)

**Comment by Pigeo** [comment]
Hello @dnoneill, I'm glad to know we are the number 1 team with the most annotations in Annonatate 😜
Joke aside, I confirm you it's fixed.
Thank you for your responsiveness!

**Comment by dnoneill** [comment]
@Pigeo You definitely are. I remember when I wrote the code I thought 1000 entries should be enough, I will cross that bridge if we are lucky enough to have users who get to it and we did :).  Of course. I really appreciate you letting me know about the issues so I don't always have to catch them myself.
